app/views/forms.py
from wtforms import Form, validators
from wtforms import TextField

#--------------------------------------------------
#
#                   Search Form
#
#--------------------------------------------------


class SearchForm(Form):
    search_terms = TextField("", [validators.Required(),
                             validators.Length(min=2, max=75)])

app/__init__.py
from flask import Flask

app = Flask(__name__)
app.config.from_object("config")

# ======================
# = Register Bluprints =
# ======================
from views.search import search
app.register_blueprint(search)

app/views/search.py
from flask import render_template, redirect, url_for, request, Blueprint

from app import app
from forms import SearchForm
from app.movie_service.netflix import NetflixRESTfulAPI as NT_API
from app.movie_service.rottentomatoes import RottenTomatoesAPI as RT_API


search = Blueprint("search", __name__, url_prefix="/search")

# Rotten Tomatoes API, Netflix API
RT = RT_API(app.config["ROTTEN_TOMATOES_KEY"])
NT = NT_API(app.config["NETFLIX_CONSUMER_KEY"],
            app.config["NETFLIX_SHARED_SECRET"])


# ------------------------------------------------------------
#                        Search Views
# ------------------------------------------------------------

@search.route("/", methods=["POST", "GET"])
def index():
    form = SearchForm(request.form)

    if request.method == "POST" and form.validate():
        return redirect(url_for("search.search_results",
                        search_term=form.search_terms.data))

    return render_template("index.html", form=form, title="Home")


@search.route("/<search_term>", methods=["GET"])
def search_results(search_term):

    results = NT.search_by_title(str(search_term))
    lst_results, num_results = results[0], results[1]

    if num_results == 1:
        return redirect(url_for("movies_series",
                                n_id_type=lst_results[0]["id_type"],
                                n_id=lst_results[0]["id"]))
    else:
        return render_template("search_results.html",
                               lst_results=lst_results,
                               num_results=num_results,
                               search_term=search_term)


@search.route("/result/<n_id_type>-<n_id>", methods=["GET"])
def movies_series(n_id_type, n_id):

    result = NT.search_by_id(n_id_type, n_id)

    if n_id_type == "movies":
        #Get movie title when selected from Netflix
        title = result["title"]["regular"]
        res = RT.search_by_title(title)

        if res["links"]["reviews"]:
            reviews = RT.get_movie_reviews(res["links"]["reviews"])
            return render_template("result.html", result=result,
                                   reviews=reviews)
        else:
            return render_template("result.html", result=result, reviews=None)

    return render_template("result.html", result=result, reviews=None)

app/templates/_formhelpers.html
{% macro render_field(field) %}

<dt>{{ field.label }}
<dd>{{ field(**kwargs) | safe }}
	{% if field.errors %}
	<ul class=errors>
		{% for error in field.errors %}
			<li>{{ error }}</li>
		{% endfor %}
	</ul>
	{% endif %}
</dd>

{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">

    	<link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/static/css/bootstrap.css" rel="stylesheet" media="screen">

        <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    	{% if title%}
    		<title>{{ title }} - flixList - Search once</title>
    	{% else %}
    		<title>flixList - Search once</title>
    	{% endif %}

    </head>
<body>
    <div class='container'>

    	{% block content %} {% endblock %}

        {% include 'footer.html' %}

    </div>


</body>
</html>

app/templates/footer.html
<div>

  <hr>

    <div class="masthead">

        <ul class="nav nav-pills pull-right">
          <li><a href="{{ url_for('search.index') }}">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>

        <h3 class="muted">FlixList</h3>

    </div>

</div>

app/templates/index.html
<!-- extend from base layout -->
{% extends "base.html" %}

{% block content %}

	<legend style="text-align: center;">Find if your Movies, TV Shows are on <img src="/static/img/netflix.png"></legend>
	{% from "_formhelpers.html" import render_field %}
	<form method=post action="" class="form-inline" style="text-align: center;">

		<dl style="text-align: center;" >

			{{ render_field(form.search_terms) }}
			<br>
			<input type="submit" value="Search" class="btn btn-large btn-success">

		</dl>

	</form>

{% endblock %}

app/templates/result.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}


<div class="row">
    <div class="span12">
        <h1 style="margin-bottom:0;">{{ result.title.regular }}</h1>
        <br>
    </div>
    <div class="span4">
        <img src="{{ result.box_art.large}}" alt="{{ result.title.regular }}" class="img-rounded">
        <br>
        <h4>{{ result.release_year }}</h4>

        <!-- Netflix Rating / Rating -->
        <h5>

            {{ result.average_rating }} stars out of 5
            <br>
            {% if result.category[0]['term'] %}
                Rated: {{ result.category[0]['term'] }}
            {% else %}
                Rated: N/A
            {% endif %}

        </h5>

    </div>

    <div class="span8">

        <h3>Available on:</h3>

        <table class="table">
            <tr>
                <th style="text-align:center;" >INSTANT </th>
                <th style="text-align:center;">DVD </th>
                <th style="text-align:center;">Blu-ray: </th>
            </tr>
            <tr>
                <td class="text-info" style="text-align:center;">
                    {% if "instant" in  result.formt %}
                        <b>Yes</b>
                    {% else %}
                        <b>No</b>
                    {% endif %}
                </td>

                <td class="text-info" style="text-align:center;">
                    {% if "DVD" in  result.format %}
                        <b>Yes</b>
                    {% else %}
                        <b>No</b>
                    {% endif %}
                </td>

                <td class="text-info" style="text-align:center;">
                    {% if "Blu-ray" in  result.format %}
                        <b>Yes</b>
                    {% else %}
                        <b>No</b>
                    {% endif %}
                </td>
            </tr>

        </table>
        <hr>

        <p>
            <!-- Synopsis -->
            {% if result.synopsis %}

                {{ result.synopsis }}

            {% else %}

                Netflix doesn't have a description for this title.

            {% endif %}

        </p>

        <!-- Category -->
        <h5>Category:</h5>

        <ul class="inline">

            {% for i in range(1, result.category|length) %}

                <li class="text-info">{{ result.category[i]['term'] }}</li>

            {% endfor %}

        </ul>


        <div class="row-fluid">
            <div class="span6">
                <!-- Cast -->
                <h3>Cast:</h3>

                <ul >
                    {% if result.cast == None %}

                        <li>Not Available</li>

                    {% else %}

                        {% for actor in result.cast %}

                            <li>{{ actor }}</li>

                        {% endfor %}

                    {% endif %}

                </ul>
            </div>

            <div class="span6">
                <!-- Director -->
                <h3>Director:</h3>

                <ul>
                    {% if result.directors == None %}

                        <li>Not Available</li>

                    {% else %}

                        {% for director in result.directors %}

                            <li>{{ director }}</li>

                        {% endfor %}

                    {% endif %}

                </ul>

                <!-- Awards -->
                <h3>Awards:</h3>
                <ul>
                    {% if result.awards == None %}
                        <li>N/A</li>
                    {% else %}

                        {% for award in result.awards %}

                            <li>{{ award }}</li>

                        {% endfor %}

                    {% endif %}

                </ul>
            </div>
        </div>

        <div>
            <h4> <img src="/static/img/rotten_tomatoes.png" alt="Rotten Tomatoes" width="20" height="20"> Reviews from RottenTomatoes: </h4>
            {% if reviews != None %}
                <dl class="dl-horizontal" style="margin-right:30px">
                {% for review in reviews %}
                    <dt>{{ review.critic }}</dt>
                    <dd>{{  review.quote }}</dd>
                    <br>
                {% endfor %}
                </dl>
            {% else %}
                Ooops! There are no reviews for {{ result.title.regular }}
            {% endif %}

        </div>

    </div>


    <div class="span12">
        <!-- <a href="">Netflix Link</a> -->
        <!-- <a href="">Official Website</a> -->
        <br>
    </div>
</div>



{% endblock %}

app/templates/search_results.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}

<h3>{{ num_results }} results for "{{ search_term }}":</h3>

<table class="table table-hover">

    <tr>

        <th>Art/Cover</th>
        <th>Title</th>

    </tr>

    {% for r in lst_results %}

    <tr>

        <td><img src="{{ r.box_art.large }}" alt="{{ r.title.regular }}"></td>
        <td><a href="{{ url_for('search.movies_series', n_id=r.id, n_id_type=r.id_type) }}">{{r.title.regular}}</a></td>


    </tr>

    {% endfor %}

</table>

{% endblock %}